name: flutter_scroll_date_picker
description: A customizable and easy-to-use date picker library for Flutter. Compatible with Android & iOS & Web.
version: 0.0.2
homepage: https://github.com/devxhub/flutter_date_picker.git

environment:
  sdk: ">=2.12.0 <4.0.0"
  flutter: ">=1.20.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

platforms:
  android:
  ios:
